services:
    _defaults:
        autowire: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [ ~, App\Entity\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
